env: "local" # dev, prod
storage_path: "./storage/storage.db"

http_server:
  address: "localhost:8082"
  read_timeout: 4s
  write_timeout: 60s

db_config:
  host: "localhost"
  port: "5436"
  username: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"